9.1
anticNVM/144-I.math.spbu pull request #8
Opened 2017-11-14 20:49 UTC by anticNVM

Hash Table with open addressing

2017-11-14 20:56 UTC, anticNVM commented on First semester/HomeWork 9/9_1/9_1.pro
> +    ../../../../../Документы/programming/cpp_builds/9_1-Desktop_Qt_5_5_1_GCC_64bit-Debug/text.in.txt
Косяк с путем до файла) В ветке поправил

2017-11-20 14:02 UTC, yurii-litvinov requested changes
На самом деле, всё очень круто, но есть что поправить

2017-11-20 14:02 UTC, yurii-litvinov commented on First semester/HomeWork 9/9_1/main.cpp
> +    if (fin.good()) {
Лучше 
```c++
if (!fin.good()) {
  cout << "ERROR: File cannot be opened." << endl;
  return 1;
}
```
--- так весь остальной код будет не в фигурных скобках, да ещё и код ошибки будем возвращать

2017-11-20 14:02 UTC, yurii-litvinov commented on First semester/HomeWork 9/9_1/main.cpp
> +                // cout << "log" << ' ';
Закомментированный код в мастере не нужен --- если нужен отладочный вывод, просто оставьте его, если нет, то удалите. Комментарии не проверяются компилятором, поэтому быстро протухают.

2017-11-20 14:02 UTC, yurii-litvinov commented on First semester/HomeWork 9/9_1/main.cpp
> +                (*getValue(word, table))++;
Можно было сделать так, чтобы getValue возвращал ссылку, а не указатель, тогда не было бы такого жутковато выглядящего разыменования

2017-11-20 14:02 UTC, yurii-litvinov commented on First semester/HomeWork 9/9_1/main.cpp
> +        getKeys(table, keys);
А чего не `const auto keys = getKeys(table);`? Мне кажется, так это выглядело бы более натурально

2017-11-20 14:02 UTC, yurii-litvinov commented on First semester/HomeWork 9/9_1/hashTable.cpp
> +            firstHash = (firstHash + secondHash) % table->array.capacity();
Это уже не совсем firstHash, а текущий индекс сегмента, который считался из первого и второго хеша. Имя переменной не очень, либо на самом деле это две переменные, скрывающиеся в одной

2017-11-20 14:02 UTC, yurii-litvinov commented on First semester/HomeWork 9/9_1/hashTable.cpp
> +}
А если ни одно из условий выхода не выполнится и управление достигнет этой точки?

2017-11-20 14:02 UTC, yurii-litvinov commented on First semester/HomeWork 9/9_1/hashTable.cpp
> +    sort(keys.begin(), keys.end());
А зачем их сортировать?

2017-11-20 14:02 UTC, yurii-litvinov commented on First semester/HomeWork 9/9_1/hashTable.cpp
> +}
Тут тоже, компилятор не одобряет, что в программе не написано, что делать, если мы таки оказались тут

2017-12-20 19:37 UTC, dpanfilyonok commented on First semester/HomeWork 9/9_1/main.cpp
> +                (*getValue(word, table))++;
Я решил возвращать указатель, чтобы возвращать nullptr, если ключа нет в таблице. Можно, наверное, в main`e каждый раз проверять наличие ключа с помощью isInTable, но в getValue уже есть функциональность, которая автоматически проверяет это "на ходу". И чтобы не делать одно и то же действие дважды, getValue сама сообщает об отсутствии элемента.

2017-12-28 06:53 UTC, yurii-litvinov approved these changes
👍

2018-02-04 14:03 UTC, merged